name: Scheduled Workflow

on: 
  push:
    branches:
      -main
  schedule:
    - cron: '*/30 10-10 * * 1-5'

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out the repo...
      uses: actions/checkout@v3
    - name: Echoing the secret...
      run: |
        echo ${{ secrets.MY_NAME }}
