name: Schema generation

on: workflow_dispatch

jobs:
  schema_generation:
    environment: dev
    runs-on: ubuntu-latest
    container: google/cloud-sdk:alpine

    steps:
    - name: Checking out repo...
      uses: actions/checkout@v3

    - name: Printing contents...
      shell: sh
      run: |
        echo "Printing current directory content..."
        ls -al *
        myvariable=${{env.MYVARIABLE}}
        echo "[*] Content : ${myvariable}"

    - name: Generating schema...
      shell: sh
      run: |
        apk add curl
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        echo ${SERVICE_ACCOUNT_KEYFILE_JSON} > client-secret.json
        gcloud auth activate-service-account --key-file client-secret.json
        gcloud config set project $PROJECT_ID
        cloud_run_url=$(gcloud run services describe ${SERVICE_NAME} --platform managed --region europe-west1 --format 'value(status.url)')
        echo "[*] Cloud Run url : ${cloud_run_url}"
        echo "creating bq tables"
        curl -X POST $cloud_run_url"/rest/deploy/setup?action=SEARCH" --fail-with-body
        echo "Completed BQ/Search schema generation"

        
      
        

    
