name: Schema generation

on: workflow_dispatch

jobs:
  schema_generation:
    environment: dev
    runs-on: ubuntu-latest
    container: google/cloud-sdk:alpine

    steps:
    - name: Checking out repo...
      uses: action/checkout@v3

    - name: Printing contents...
      shell: sh
      run: |
        echo "Printing current directory content..."
        ls -al *
        

    
