name: Schema generation

on: workflow_dispatch

jobs:
  schema_generation:
    environment: dev
    runs-on: ubuntu-latest
    container: google/cloud-sdk:alpine

    steps:
    - name: Printing contents...
      shell: sh
      run: |
        echo "Printing current directory content..."
        myvariable="${{vars.MYVARIABLE}}"
        echo "[*] Content : ${myvariable}"
        echo "${myvariable}"

    - name: Generating schema...
      shell: sh
      run: |
        apk add curl
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        echo ${{vars.SERVICE_ACCOUNT_KEYFILE_JSON}} > client-secret.json
        more client-secret.json

        
      
        

    
